user.Current and sudo check
fishworks/gofish pull request #188
Opened 2021-09-29 04:36 UTC by azilber

Sudo check and partial switch to user.Current

2021-09-29 04:37 UTC, azilber commented
This is a cleanup of https://github.com/fishworks/gofish/pull/186

2021-10-22 01:53 UTC, bacongobbler requested changes
can you write some tests to cover these changes? Perhaps some refactoring is in order.

2021-12-01 14:12 UTC, azilber commented on cmd/gofish/ensure_unix.go
> +	if i, _ := strconv.Atoi(curUser.Uid); i == 0 {
fixed

2021-12-01 14:12 UTC, azilber commented on cmd/gofish/ensure_unix.go
> +	curGroup, _ := user.LookupGroupId(curUser.Gid)
done

2021-12-03 09:07 UTC, azilber commented
> can you write some tests to cover these changes? Perhaps some refactoring is in order.

Unfortunately I don't have the bandwidth right now to setup any testing.  This was a simple quality of life patch.

2022-04-07 09:25 UTC, closed without merging